### ISSUE TITLE
changing SEFD value has almost no effect

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/spiel#9]
first image is with `sefd` of `0.0042`, second one is with 4200

![screenshot from 2018-06-26 11-45-59](https://user-images.githubusercontent.com/326308/41903579-945509dc-7936-11e8-9e22-f3c9c22b7b5b.png)
![screenshot from 2018-06-26 11-46-05](https://user-images.githubusercontent.com/326308/41903580-946bd108-7936-11e8-8c5f-d531877be9e2.png)

**Comment by sphemakh** [comment]
The image is dominated by PSF sidelobes, this is why changing the SEFD is not making much of a difference. This is typical for kat-7 since it has a crappy PSF
